[general]
caption_extension = '.txt'
keep_tokens = 1

[[datasets]]
resolution = [768, 768]
keep_tokens = 2
# train_batch_size = 16
batch_size = 16
bucket_reso_steps = 64
enable_bucket = true
min_bucket_reso = 512
max_bucket_reso = 1536
validation_seed = 6789
validation_split = 0.2

 [[datasets.subsets]]
 image_dir = '/home/ubuntu/data/ds3'
 num_repeats = 1
 keep_tokens = 2
